create table if not exists public.temporary_admin_social_participation_events_v2 (
  id bigint generated by default as identity primary key,
  social_event_id text not null,
  subject_type text not null check (subject_type in (
    'temporary_submission',
    'legacy_snapshot',
    'restored_application'
  )),
  subject_id text not null,
  previous_status text check (
    previous_status is null or previous_status in (
      'applied',
      'reviewing',
      'selected',
      'waitlisted',
      'payment_pending',
      'paid',
      'confirmed',
      'attended',
      'no_show',
      'cancelled'
    )
  ),
  status text not null check (status in (
    'applied',
    'reviewing',
    'selected',
    'waitlisted',
    'payment_pending',
    'paid',
    'confirmed',
    'attended',
    'no_show',
    'cancelled'
  )),
  reason text,
  actor_user_id uuid not null,
  actor_email text not null,
  created_at timestamptz not null default now(),
  check (
    status not in ('cancelled', 'no_show')
    or nullif(btrim(reason), '') is not null
  )
);

create index if not exists temporary_admin_social_participation_v2_subject_idx
  on public.temporary_admin_social_participation_events_v2 (
    social_event_id,
    subject_type,
    subject_id,
    created_at desc
  );

create index if not exists temporary_admin_social_participation_v2_status_idx
  on public.temporary_admin_social_participation_events_v2 (
    status,
    created_at desc
  );

alter table public.temporary_admin_social_participation_events_v2
  enable row level security;

comment on table public.temporary_admin_social_participation_events_v2 is
  'Append-only social participation and manual payment state. References existing Event and Applicant subjects without copying profile, payment, document, or payload data.';
