create extension if not exists pgcrypto;

create table if not exists public.temporary_admin_subject_workflows (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null check (subject_type in ('temporary_submission', 'legacy_snapshot', 'restored_application')),
  subject_id text not null,
  workflow_stage text not null check (workflow_stage in (
    'new',
    'first_review',
    'secondary_send_needed',
    'secondary_waiting',
    'secondary_in_progress',
    'secondary_review_needed',
    'approved',
    'hold',
    'rejected',
    'member_converted'
  )),
  decision text check (decision is null or decision in ('approved', 'hold', 'rejected', 'materials_requested')),
  reason text,
  assigned_to text,
  reviewed_by_user_id uuid,
  reviewed_by_email text,
  reviewed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (subject_type, subject_id)
);

create index if not exists temporary_admin_subject_workflows_stage_idx
  on public.temporary_admin_subject_workflows (workflow_stage, updated_at desc);
create index if not exists temporary_admin_subject_workflows_assignee_idx
  on public.temporary_admin_subject_workflows (assigned_to, updated_at desc);

create table if not exists public.temporary_admin_workflow_events (
  id bigint generated by default as identity primary key,
  subject_type text not null check (subject_type in ('temporary_submission', 'legacy_snapshot', 'restored_application')),
  subject_id text not null,
  previous_stage text,
  workflow_stage text not null check (workflow_stage in (
    'new',
    'first_review',
    'secondary_send_needed',
    'secondary_waiting',
    'secondary_in_progress',
    'secondary_review_needed',
    'approved',
    'hold',
    'rejected',
    'member_converted'
  )),
  decision text check (decision is null or decision in ('approved', 'hold', 'rejected', 'materials_requested')),
  reason text,
  assigned_to text,
  actor_user_id uuid not null,
  actor_email text not null,
  created_at timestamptz not null default now()
);

create index if not exists temporary_admin_workflow_events_subject_idx
  on public.temporary_admin_workflow_events (subject_type, subject_id, created_at desc);
create index if not exists temporary_admin_workflow_events_created_idx
  on public.temporary_admin_workflow_events (created_at desc);

create table if not exists public.temporary_secondary_profile_reviews (
  id uuid primary key default gen_random_uuid(),
  form_id uuid not null references public.temporary_secondary_profile_forms(id) on delete restrict,
  subject_type text not null check (subject_type in ('temporary_submission', 'legacy_snapshot', 'restored_application')),
  subject_id text not null,
  result text not null check (result in ('approved', 'hold', 'rejected', 'materials_requested')),
  reason text,
  previous_result text check (previous_result is null or previous_result in ('approved', 'hold', 'rejected', 'materials_requested')),
  reviewed_by_user_id uuid not null,
  reviewed_by_email text not null,
  reviewed_at timestamptz not null default now(),
  check (result = 'approved' or nullif(btrim(reason), '') is not null)
);

create index if not exists temporary_secondary_profile_reviews_form_idx
  on public.temporary_secondary_profile_reviews (form_id, reviewed_at desc);
create index if not exists temporary_secondary_profile_reviews_subject_idx
  on public.temporary_secondary_profile_reviews (subject_type, subject_id, reviewed_at desc);

create table if not exists public.temporary_admin_schedule_events (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null check (subject_type in ('temporary_submission', 'legacy_snapshot', 'restored_application')),
  subject_id text not null,
  schedule_type text not null check (schedule_type in ('consultation', 'next_contact')),
  event_action text not null check (event_action in ('created', 'updated', 'cancelled')),
  scheduled_at timestamptz,
  replaces_event_id uuid references public.temporary_admin_schedule_events(id) on delete restrict,
  reason text,
  actor_user_id uuid not null,
  actor_email text not null,
  created_at timestamptz not null default now(),
  check (event_action = 'cancelled' or scheduled_at is not null),
  check (event_action = 'created' or replaces_event_id is not null)
);

create index if not exists temporary_admin_schedule_events_subject_idx
  on public.temporary_admin_schedule_events (subject_type, subject_id, schedule_type, created_at desc);
create index if not exists temporary_admin_schedule_events_due_idx
  on public.temporary_admin_schedule_events (scheduled_at, created_at desc);

create table if not exists public.temporary_admin_member_events (
  id bigint generated by default as identity primary key,
  subject_type text not null check (subject_type in ('temporary_submission', 'legacy_snapshot', 'restored_application')),
  subject_id text not null,
  review_id uuid references public.temporary_secondary_profile_reviews(id) on delete restrict,
  event_type text not null check (event_type in ('approved', 'converted', 'status_changed')),
  previous_status text,
  member_status text not null check (member_status in (
    'approval_pending',
    'converted',
    'matchable',
    'matching',
    'meeting_scheduled',
    'paused',
    'ended'
  )),
  reason text,
  actor_user_id uuid not null,
  actor_email text not null,
  created_at timestamptz not null default now()
);

create index if not exists temporary_admin_member_events_subject_idx
  on public.temporary_admin_member_events (subject_type, subject_id, created_at desc);
create index if not exists temporary_admin_member_events_status_idx
  on public.temporary_admin_member_events (member_status, created_at desc);

create table if not exists public.temporary_admin_matching_cases (
  id uuid primary key default gen_random_uuid(),
  male_subject_type text not null check (male_subject_type in ('temporary_submission', 'legacy_snapshot', 'restored_application')),
  male_subject_id text not null,
  female_subject_type text not null check (female_subject_type in ('temporary_submission', 'legacy_snapshot', 'restored_application')),
  female_subject_id text not null,
  status text not null default 'candidate_selected' check (status in (
    'candidate_selected',
    'male_reviewing',
    'male_accepted',
    'male_rejected',
    'scheduling',
    'meeting_confirmed',
    'meeting_completed',
    'cancelled',
    'closed'
  )),
  created_by_user_id uuid not null,
  created_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists temporary_admin_matching_cases_male_idx
  on public.temporary_admin_matching_cases (male_subject_type, male_subject_id, created_at desc);
create index if not exists temporary_admin_matching_cases_female_idx
  on public.temporary_admin_matching_cases (female_subject_type, female_subject_id, created_at desc);
create index if not exists temporary_admin_matching_cases_status_idx
  on public.temporary_admin_matching_cases (status, updated_at desc);

create table if not exists public.temporary_admin_matching_events (
  id bigint generated by default as identity primary key,
  matching_case_id uuid not null references public.temporary_admin_matching_cases(id) on delete restrict,
  previous_status text,
  status text not null check (status in (
    'candidate_selected',
    'male_reviewing',
    'male_accepted',
    'male_rejected',
    'scheduling',
    'meeting_confirmed',
    'meeting_completed',
    'cancelled',
    'closed'
  )),
  reason text,
  scheduled_at timestamptz,
  actor_user_id uuid not null,
  actor_email text not null,
  created_at timestamptz not null default now(),
  check (status <> 'male_rejected' or nullif(btrim(reason), '') is not null)
);

create index if not exists temporary_admin_matching_events_case_idx
  on public.temporary_admin_matching_events (matching_case_id, created_at desc);
create index if not exists temporary_admin_matching_events_created_idx
  on public.temporary_admin_matching_events (created_at desc);

create table if not exists public.temporary_admin_social_events (
  id bigint generated by default as identity primary key,
  social_event_id text not null,
  subject_type text not null check (subject_type in ('temporary_submission', 'legacy_snapshot', 'restored_application')),
  subject_id text not null,
  previous_status text,
  status text not null check (status in ('applied', 'reviewing', 'selected', 'waitlisted', 'confirmed', 'cancelled', 'attended', 'no_show')),
  reason text,
  actor_user_id uuid not null,
  actor_email text not null,
  created_at timestamptz not null default now()
);

create index if not exists temporary_admin_social_events_subject_idx
  on public.temporary_admin_social_events (social_event_id, subject_type, subject_id, created_at desc);
create index if not exists temporary_admin_social_events_status_idx
  on public.temporary_admin_social_events (status, created_at desc);

create table if not exists public.temporary_admin_audit_events (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  actor_user_id uuid not null,
  actor_email text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists temporary_admin_audit_events_created_idx
  on public.temporary_admin_audit_events (created_at desc);
create index if not exists temporary_admin_audit_events_entity_idx
  on public.temporary_admin_audit_events (entity_type, entity_id, created_at desc);

alter table public.temporary_admin_subject_workflows enable row level security;
alter table public.temporary_admin_workflow_events enable row level security;
alter table public.temporary_secondary_profile_reviews enable row level security;
alter table public.temporary_admin_schedule_events enable row level security;
alter table public.temporary_admin_member_events enable row level security;
alter table public.temporary_admin_matching_cases enable row level security;
alter table public.temporary_admin_matching_events enable row level security;
alter table public.temporary_admin_social_events enable row level security;
alter table public.temporary_admin_audit_events enable row level security;

comment on table public.temporary_admin_subject_workflows is
  'Current temporary admin workflow projection. References an existing Applicant subject without copying profile PII.';
comment on table public.temporary_admin_workflow_events is
  'Append-only workflow stage history for the temporary admin.';
comment on table public.temporary_secondary_profile_reviews is
  'Append-only review decisions for already-submitted secondary forms. Submitted payloads remain immutable.';
comment on table public.temporary_admin_schedule_events is
  'Append-only consultation and next-contact schedule history; cancellation never deletes prior events.';
comment on table public.temporary_admin_member_events is
  'Append-only approved-member conversion and operating status history using Applicant references only.';
comment on table public.temporary_admin_matching_cases is
  'Male-choice IRUM 1:1 matching cases. Applicant profile data is never copied.';
comment on table public.temporary_admin_matching_events is
  'Append-only male-choice matching status history. No female accept or reject state exists.';
comment on table public.temporary_admin_social_events is
  'Append-only temporary social participation state keyed by a real Event ID and Applicant reference.';
comment on table public.temporary_admin_audit_events is
  'Append-only operational audit without raw tokens, signed URLs, storage paths, or Applicant payloads.';
